server:
  port: 8484
spring:
  application:
    name: mall-server
  servlet:
    #文件上传限制
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 10MB

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    username:
    password:
    url:
mybatis-plus:
  mapper-locations: classpath:com/syh/mall/mapper/xml/*.xml
  type-aliases-package: com.syh.mall.pojo
  configuration:
    auto-mapping-behavior: full
    map-underscore-to-camel-case: true

wx:
  appId:
  secret:

aliyun:
  accessKeyId:
  accessKeySecret:
  oss:
    endpoint:
    bucketName:

